// Generated by lpg-modeler. Target: ladybug (LadybugDB).
// Model: social <https://example.org/vocab/social#>
//
// Abstract node types are flattened to one table per concrete type, with
// inherited properties copied down. See lat.md/emitters#Ladybug Target.

// Abstract, no table emitted: Party

CREATE NODE TABLE IF NOT EXISTS Car (
  vin STRING,
  seats INT64,
  PRIMARY KEY(vin)
);

CREATE NODE TABLE IF NOT EXISTS Company (
  vat STRING,
  id STRING,
  PRIMARY KEY(id)
);

CREATE NODE TABLE IF NOT EXISTS Person (
  // UNENFORCED: 'email' is required in the model; LadybugDB has no NOT NULL.
  // UNENFORCED: 'email' is unique in the model; only the primary key is unique.
  email STRING,
  born DATE,
  // UNENFORCED: 'createdAt' is required in the model; LadybugDB has no NOT NULL.
  createdAt TIMESTAMP_TZ,
  id STRING,
  PRIMARY KEY(id)
);

CREATE REL TABLE IF NOT EXISTS KNOWS (
  FROM Person TO Person,
  since DATE
);

CREATE REL TABLE IF NOT EXISTS LIKES (
  FROM Person TO Company
);

CREATE REL TABLE IF NOT EXISTS OWNS (
  // 'Party' and/or 'Car' are abstract; expanded to 2 endpoint pairs.
  FROM Company TO Car,
  FROM Person TO Car,
  since DATE
);
